baseURL: https://ivostork.com
languageCode: en-us
defaultContentLanguage: en
title: Ivo Stork - Research & Webdesign
theme: cupper-hugo-theme
googleAnalytics: UA-188424174-1
# disqusShortname: yourdiscussshortname
enableGitInfo: false
enableRobotsTXT: true

taxonomies:
  tag: tags

# permalinks:
#   post: /:filename/

imaging:
  quality: 99

params:
  # description: An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project.
  homeMetaContent: Custom tailored websites.
  footer: Ivo Stork - ivos.stork@gmail.com -  +420 728 641 141 -  www.linkedin.com/in/ivo-stork/ 
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  # codePenUser: someUser
  katex: false
  hideHeaderLinks: true
  search: false
  showThemeSwitcher: false
  moveFooterToHeader: false
  customCss:
    - css/custom_01.css
    # - css/custom_02.css
  
  # customJs:
    # - js/custom_01.js
    # - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    # - name: Blog
    #   url: /post/
    #   weight: 2
    # - name: Tags
    #   url: /tags/
    #   weight: 3
    - name: Free website audit
      url: /free-web-audit/
      weight: 2
    - name: Contact
      url: /contact/
      weight: 3
    # - name: RSS
    #   url: /index.xml
    #   weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2